# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WurbSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_key', models.CharField(max_length=512)),
                ('settings_value', models.CharField(max_length=1024)),
            ],
        ),
    ]
